"""TSSS Brain Service — AI-assisted research workflow for TSSS valuation.

OmniRoute is the LLM gateway only. This service does NOT claim it performs
verified web search by itself. The system clearly separates:
1. Search query suggestions generated by LLM.
2. Candidate raw text/URL provided by user or future crawler.
3. Extracted/normalized comparable data.
4. Hard-filter/scoring/final analyst selection.
"""

import json
import re
from typing import Any

from app.models.candidate import RawCandidate
from app.models.project import SubjectAsset
from app.services.omni_client import GatewayUnavailableError, OmniRouteClient

# ---------------------------------------------------------------------------
# Deterministic fallback responses when LLM is unavailable
# ---------------------------------------------------------------------------

_FALLBACK_QUERIES = {
    "search_queries": [
        "Nhà đất bán tại khu vực [market_area], loại đất [land_type]",
        "Đất [land_type] thổ cư [market_area] diện tích [size] m²",
        "Bất động sản [land_type] [market_area] giá tốt",
        "So sánh giá đất [land_type] khu vực [market_area]",
        "Giao dịch [land_type] thành công [market_area]",
    ],
    "market_area": None,
    "land_type": None,
    "size_range_min": None,
    "size_range_max": None,
    "price_basis": "VND/m²",
    "source_caution": (
        "Verify listing data independently. "
        "Do not rely solely on asking prices without cross-checking."
    ),
}

_FALLBACK_EXTRACT = {
    "market_area": None,
    "land_type": None,
    "planning_segment": None,
    "size_sqm": None,
    "unit_price": None,
    "asking_price": None,
    "source_quality": None,
    "draft_note": "LLM gateway unavailable; no extraction performed.",
    "warnings": [
        "OmniRoute gateway unavailable. No extraction performed.",
        "This candidate will not have normalized fields until extraction is run.",
    ],
}

# ---------------------------------------------------------------------------
# Known land-type codes commonly found in Vietnamese listings
# ---------------------------------------------------------------------------
_VIETNAMESE_LAND_TYPES = [
    "ONT", "ODT", "CLN", "BHK", "TMDV", "SKC", "NK", "LNK",
    "PNN", "DGT", "DDT", "NTS", "RSX", "MNC", "LUC", "HNK",
]

_FALLBACK_RATIONALE = {
    "rationale": "LLM gateway unavailable; no rationale generated.",
    "strengths": [],
    "weaknesses": [],
    "adjustment_notes": [],
    "warnings": ["OmniRoute gateway unavailable. No rationale generated."],
}

# ---------------------------------------------------------------------------
# Public Service Functions
# ---------------------------------------------------------------------------


def build_tsss_search_brief(subject_asset: SubjectAsset) -> dict[str, Any]:
    """Build a research brief for the given subject asset.

    Returns a structured dict with subject asset summary and a Vietnamese brief.
    Does NOT call LLM; purely deterministic.
    """
    return {
        "subject_asset": {
            "address": subject_asset.address,
            "market_area": subject_asset.market_area,
            "land_type": subject_asset.land_type,
            "planning_segment": subject_asset.planning_segment,
            "size_sqm": subject_asset.size_sqm,
        },
        "brief": (
            f"Tìm kiếm bất động sản so sánh tại khu vực {subject_asset.market_area}, "
            f"loại đất {subject_asset.land_type}, "
            f"diện tích khoảng {subject_asset.size_sqm} m²."
        ),
    }


def suggest_search_queries(subject_asset: SubjectAsset) -> dict[str, Any]:
    """Generate search query suggestions using OmniRoute LLM.

    Returns structured dict with:
      - search_queries: list of suggested search query strings
      - market_area / land_type / size_range_min / size_range_max / price_basis
      - source_caution: warning about source verification
      - warnings: list if LLM fallback was used

    On LLM failure, returns deterministic fallback with warnings.
    """
    query_hint = _subject_query_hint(subject_asset)

    try:
        client = OmniRouteClient()
        system_msg = (
            "Bạn là trợ lý nghiên cứu thẩm định giá (TSSS Valuation Assistant). "
            "Luôn trả lời bằng tiếng Việt. "
            "Trả về JSON hợp lệ với các key: "
            "search_queries (mảng 5 chuỗi), market_area, land_type, "
            "size_range_min (số hoặc null), size_range_max (số hoặc null), "
            "price_basis (string), source_caution (string)."
        )
        user_msg = (
            f"Tài sản thẩm định:\n"
            f"- Địa chỉ: {subject_asset.address}\n"
            f"- Khu vực: {subject_asset.market_area}\n"
            f"- Loại đất: {subject_asset.land_type}\n"
            f"- Quy hoạch: {subject_asset.planning_segment or 'N/A'}\n"
            f"- Diện tích: {subject_asset.size_sqm} m²\n\n"
            f"Đề xuất 5 truy vấn tìm kiếm bất động sản so sánh phù hợp. "
            f"Xác định market_area, land_type, khoảng diện tích, "
            f"cơ sở giá và cảnh báo nguồn."
        )
        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg},
        ]
        result = client.chat_completion(messages, temperature=0.3, response_format_json=True)
        content = result.get("choices", [{}])[0].get("message", {}).get("content", "{}")
        parsed = json.loads(content)

        # Ensure all keys exist
        return {
            "search_queries": parsed.get("search_queries", query_hint["search_queries"]),
            "market_area": parsed.get("market_area", subject_asset.market_area),
            "land_type": parsed.get("land_type", subject_asset.land_type),
            "size_range_min": parsed.get("size_range_min"),
            "size_range_max": parsed.get("size_range_max"),
            "price_basis": parsed.get("price_basis", "VND/m²"),
            "source_caution": parsed.get(
                "source_caution",
                "Xác minh dữ liệu niêm yết độc lập trước khi sử dụng.",
            ),
            "warnings": [],
        }
    except (GatewayUnavailableError, json.JSONDecodeError, KeyError, TypeError) as exc:
        fallback = dict(_FALLBACK_QUERIES)
        fallback["search_queries"] = query_hint["search_queries"]
        fallback["market_area"] = subject_asset.market_area
        fallback["land_type"] = subject_asset.land_type
        fallback["size_range_min"] = max(0, subject_asset.size_sqm * 0.5)
        fallback["size_range_max"] = subject_asset.size_sqm * 2.0
        warning_msg = (
            f"OmniRoute LLM unavailable ({type(exc).__name__}: {exc}). "
            f"Using deterministic fallback."
        )
        fallback["warnings"] = [warning_msg]
        return fallback


def extract_candidate_from_raw_text(
    raw_text: str,
    source_url: str | None,
    subject_asset: SubjectAsset,
) -> dict[str, Any]:
    """Extract normalized candidate fields from raw listing text using OmniRoute LLM.

    Args:
        raw_text: Raw listing text (required).
        source_url: Optional source URL.
        subject_asset: The subject asset for context.

    Returns:
        dict with extracted fields (market_area, land_type, planning_segment,
        size_sqm, unit_price, asking_price, source_quality, draft_note) and
        warnings list. Missing fields are null.

    On LLM failure, returns deterministic fallback with warnings.
    """
    if not raw_text or not raw_text.strip():
        fallback = dict(_FALLBACK_EXTRACT)
        fallback["warnings"] = ["raw_text is empty or missing. No extraction possible."]
        if source_url:
            fallback["source_url"] = source_url
        return fallback

    try:
        client = OmniRouteClient()
        system_msg = (
            "Bạn là trợ lý trích xuất dữ liệu thẩm định giá (TSSS Extraction Assistant). "
            "Trích xuất thông tin bất động sản từ văn bản niêm yết. "
            "Trả về JSON hợp lệ. "
            "Nếu thông tin không có, trả về null cho trường đó. "
            "Không bịa đặt dữ liệu. "
            "Các trường: market_area (string), land_type (string), "
            "planning_segment (string hoặc null), size_sqm (number hoặc null), "
            "unit_price (number VND/m² hoặc null), asking_price (number VND hoặc null), "
            "source_quality ('HIGH'|'MEDIUM'|'LOW'|'WEAK'|null), "
            "draft_note (string mô tả ngắn bằng tiếng Việt)."
        )
        user_msg = (
            f"Tài sản thẩm định (context):\n"
            f"- Khu vực: {subject_asset.market_area}\n"
            f"- Loại đất: {subject_asset.land_type}\n"
            f"- Diện tích: {subject_asset.size_sqm} m²\n\n"
            f"Văn bản niêm yết:\n{raw_text}\n\n"
            f"Trích xuất thông tin bất động sản so sánh từ văn bản trên."
        )
        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg},
        ]
        result = client.chat_completion(messages, temperature=0.1, response_format_json=True)
        content = result.get("choices", [{}])[0].get("message", {}).get("content", "{}")
        parsed = json.loads(content)

        extracted = {
            "market_area": parsed.get("market_area"),
            "land_type": parsed.get("land_type"),
            "planning_segment": parsed.get("planning_segment"),
            "size_sqm": _safe_float(parsed.get("size_sqm")),
            "unit_price": _safe_float(parsed.get("unit_price")),
            "asking_price": _safe_float(parsed.get("asking_price")),
            "source_quality": parsed.get("source_quality"),
            "draft_note": parsed.get("draft_note"),
        }

        if source_url:
            extracted["source_url"] = source_url

        # Collect warnings for missing critical fields
        warnings = []
        if not extracted["market_area"]:
            warnings.append("market_area not found in raw text.")
        if not extracted["land_type"]:
            warnings.append("land_type not found in raw text.")
        if not extracted["size_sqm"]:
            warnings.append("size_sqm not found in raw text.")
        if not extracted["unit_price"]:
            warnings.append("unit_price not found in raw text.")
        extracted["warnings"] = warnings

        return extracted

    except (GatewayUnavailableError, json.JSONDecodeError, KeyError, TypeError) as exc:
        fallback = dict(_FALLBACK_EXTRACT)
        if source_url:
            fallback["source_url"] = source_url
        warning_msg = (
            f"OmniRoute LLM unavailable ({type(exc).__name__}: {exc}). "
            f"Using deterministic fallback parsing."
        )
        fallback["warnings"] = [warning_msg]

        # Attempt deterministic parsing as fallback
        parsed = _fallback_parse_raw_text(raw_text, subject_asset)
        for key in ("market_area", "land_type", "planning_segment",
                     "size_sqm", "unit_price", "asking_price", "source_quality"):
            if parsed.get(key) is not None:
                fallback[key] = parsed[key]
                msg = f"Deterministic fallback resolved: {key}={parsed[key]}"
                fallback["warnings"].append(msg)

        return fallback


def generate_candidate_rationale(
    candidate: RawCandidate,
    subject_asset: SubjectAsset,
    rule_assessment: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Generate a rationale for a candidate using OmniRoute LLM.

    Args:
        candidate: The raw candidate to evaluate.
        subject_asset: The subject asset for comparison.
        rule_assessment: Optional dict with rule assessment results.

    Returns:
        dict with rationale, strengths, weaknesses, adjustment_notes, warnings.

    On LLM failure, returns deterministic fallback with warnings.
    """
    try:
        client = OmniRouteClient()
        rule_context = ""
        if rule_assessment:
            rule_context = (
                "\nKết quả đánh giá quy tắc:\n"
                f"{json.dumps(rule_assessment, ensure_ascii=False, indent=2)}"
            )

        system_msg = (
            "Bạn là trợ lý phân tích thẩm định giá (TSSS Rationale Assistant). "
            "Đánh giá bất động sản so sánh dựa trên tài sản thẩm định. "
            "Trả về JSON hợp lệ. "
            "Các trường: rationale (string), strengths (mảng string), "
            "weaknesses (mảng string), adjustment_notes (mảng string)."
        )
        user_msg = (
            f"Tài sản thẩm định:\n"
            f"- Địa chỉ: {subject_asset.address}\n"
            f"- Khu vực: {subject_asset.market_area}\n"
            f"- Loại đất: {subject_asset.land_type}\n"
            f"- Diện tích: {subject_asset.size_sqm} m²\n\n"
            f"Bất động sản so sánh:\n"
            f"- URL: {candidate.source_url or 'N/A'}\n"
            f"- Khu vực: {candidate.market_area or 'N/A'}\n"
            f"- Loại đất: {candidate.land_type or 'N/A'}\n"
            f"- Diện tích: {candidate.size_sqm or 'N/A'} m²\n"
            f"- Đơn giá: {candidate.unit_price or 'N/A'} VND/m²\n"
            f"- Giá chào: {candidate.asking_price or 'N/A'} VND\n"
            f"- Chất lượng nguồn: {candidate.source_quality or 'N/A'}"
            f"{rule_context}\n\n"
            f"Đưa ra đánh giá về tính phù hợp của bất động sản so sánh này."
        )
        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg},
        ]
        result = client.chat_completion(messages, temperature=0.3, response_format_json=True)
        content = result.get("choices", [{}])[0].get("message", {}).get("content", "{}")
        parsed = json.loads(content)

        return {
            "rationale": parsed.get("rationale", ""),
            "strengths": parsed.get("strengths", []),
            "weaknesses": parsed.get("weaknesses", []),
            "adjustment_notes": parsed.get("adjustment_notes", []),
            "warnings": [],
        }

    except (GatewayUnavailableError, json.JSONDecodeError, KeyError, TypeError) as exc:
        fallback = dict(_FALLBACK_RATIONALE)
        warning_msg = (
            f"OmniRoute LLM unavailable ({type(exc).__name__}: {exc}). "
            f"Using deterministic fallback."
        )
        fallback["warnings"] = [warning_msg]
        return fallback


# ---------------------------------------------------------------------------
# Internal Helpers
# ---------------------------------------------------------------------------


def _subject_query_hint(subject_asset: SubjectAsset) -> dict[str, Any]:
    """Build deterministic search query hints from subject asset data."""
    size = subject_asset.size_sqm
    area = subject_asset.market_area
    land = subject_asset.land_type
    return {
        "search_queries": [
            f"Nhà đất bán tại {area}, loại đất {land}",
            f"Đất {land} thổ cư {area} diện tích {size} m²",
            f"Bất động sản {land} {area} giá tốt",
            f"So sánh giá đất {land} khu vực {area}",
            f"Giao dịch {land} thành công {area}",
        ],
    }


def _safe_float(value: Any) -> float | None:
    """Safely convert a value to float or return None."""
    if value is None:
        return None
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


def _parse_vietnamese_number(text: str) -> float | None:
    """Parse a Vietnamese numeric expression (e.g. '11.4 tỷ', '95 triệu') to float.

    Handles both decimal separators (e.g. 11.4 → 11.4) and thousand
    separators (e.g. 1.000.000 → 1000000).
    """
    if not text:
        return None
    text = text.strip().lower().replace(",", "")
    # Ordered by descending multiplier so we match "tỷ" before plain digits
    multipliers = [
        (r'([\d.]+)\s*tỷ', 1_000_000_000),
        (r'([\d.]+)\s*triệu', 1_000_000),
        (r'([\d.]+)\s*trieu', 1_000_000),
        (r'([\d.]+)\s*nghìn', 1_000),
        (r'([\d.]+)\s*ngàn', 1_000),
    ]
    for pattern, multiplier in multipliers:
        m = re.search(pattern, text)
        if m:
            raw_num = m.group(1)
            try:
                return _parse_decimal_or_thousand(raw_num) * multiplier
            except ValueError:
                continue
    # Try bare number
    m = re.search(r'([\d.]+)', text)
    if m:
        try:
            return _parse_decimal_or_thousand(m.group(1))
        except ValueError:
            return None
    return None


def _parse_decimal_or_thousand(num_str: str) -> float:
    """Convert a string like '11.4' or '1.000.000' to float.

    - Single '.' followed by 1-2 trailing digits → decimal separator (keep).
    - Otherwise → thousand separator (remove all '.').
    """
    parts = num_str.split(".")
    if len(parts) == 2 and len(parts[1]) in (1, 2):
        # Likely a decimal separator, e.g. "11.4"
        return float(num_str)
    # Otherwise treat as thousand separators, e.g. "1.000.000"
    return float(num_str.replace(".", ""))


def _fallback_parse_raw_text(
    raw_text: str,
    subject_asset: SubjectAsset | None = None,
) -> dict[str, Any]:
    """Deterministic regex-based extraction from Vietnamese real-estate text.

    Used when the LLM gateway is unavailable.  Only fields that can be
    confidently extracted are set; everything else remains ``None``.
    """
    result: dict[str, Any] = {
        "market_area": None,
        "land_type": None,
        "planning_segment": None,
        "size_sqm": None,
        "unit_price": None,
        "asking_price": None,
        "source_quality": None,
    }

    text_lower = raw_text.lower()

    # ── size_sqm ──────────────────────────────────────────────────────
    # "diện tích 120m2", "120 m²", "120m2"
    size_patterns = [
        r'diện\s*tích\s*([\d.]+)\s*m',
        r'(\d+)\s*m[²2]',
    ]
    for pat in size_patterns:
        m = re.search(pat, text_lower)
        if m:
            try:
                result["size_sqm"] = float(m.group(1).replace(".", ""))
            except ValueError:
                pass
            if result["size_sqm"] is not None:
                break

    # ── land_type ─────────────────────────────────────────────────────
    # "đất ONT", "đất ODT", "loại đất ONT"
    # Use original (non-lowercased) text since land-type codes are uppercase
    for lt in _VIETNAMESE_LAND_TYPES:
        if re.search(rf'\b{lt}\b', raw_text, re.IGNORECASE):
            result["land_type"] = lt
            break

    # ── unit_price (VND/m²) ───────────────────────────────────────────
    # "đơn giá khoảng 95 triệu đồng/m2"
    # "đơn giá ... 95 triệu/m2"
    # "95 triệu đồng/m2"
    unit_price_patterns = [
        r'đơn\s*giá.*?([\d.]+\s*(?:triệu|tỷ|trieu)\s*(?:đồng)?\s*/?\s*m[²2])',
        r'([\d.]+\s*(?:triệu|tỷ|trieu)\s*(?:đồng)?\s*/?\s*m[²2])',
    ]
    for pat in unit_price_patterns:
        m = re.search(pat, text_lower)
        if m:
            val = _parse_vietnamese_number(m.group(1))
            if val is not None:
                result["unit_price"] = val
                break

    # ── asking_price (VND) ────────────────────────────────────────────
    # "giá bán 11.4 tỷ đồng"  OR  "giá 11.4 tỷ"
    # Avoid matching the unit_price pattern again.
    m_ask = re.search(r'giá\s*(?:bán)?\s*([\d.]+\s*(?:tỷ|triệu|trieu)\s*(?:đồng)?)', text_lower)
    if m_ask:
        val = _parse_vietnamese_number(m_ask.group(1))
        if val is not None:
            # Only accept as asking_price if it's significantly different from unit_price
            # (unit_price is VND/m², asking_price is total VND)
            if result["unit_price"] is None or abs(val - result["unit_price"]) > 1000:
                result["asking_price"] = val

    # ── market_area ───────────────────────────────────────────────────
    # Try to extract location from the beginning of the text
    # "Bán đất Phước Long, TP Thủ Đức" -> "Phước Long, TP Thủ Đức"
    m_area = re.search(
        r'(?:bán\s*(?:đất|nhà|cc|chung\s*cư)\s*)?([\w\s,]+?)'
        r'(?:\.|\s+diện\s*tích|\s+đất\s|\s+giá\s|\s+đơn\s*giá)',
        text_lower,
    )
    if m_area:
        candidate = m_area.group(1).strip().strip(",").strip()
        if candidate and len(candidate) > 3:
            result["market_area"] = candidate

    # ── source_quality ────────────────────────────────────────────────
    # Default MEDIUM if any fields were parsed; otherwise leave None
    if any(v is not None for v in result.values()):
        result["source_quality"] = "MEDIUM"

    return result
